import { BillRouteItem, PaydayInflowRule, UserCardItem, BillerCatalogItem } from '@/types/payday';

export const initialPaydayRules: PaydayInflowRule = {
  minInflowThreshold: 500000,
  narrationKeywords: ['SALARY', 'PAYROLL', 'EARNINGS', 'CONTRACT', 'INFLOW', 'SETTLEMENT'],
  executionMode: 'manual_approval', // User approval enabled
  primaryReceivingNodeId: 'gtb',
  residualStrategy: 'sweep_to_savings',
  globalFreezeActive: false,
};

export const initialUserCards: UserCardItem[] = [
  {
    id: 'card_01',
    bankName: 'GTBank',
    cardType: 'Mastercard',
    last4: '0491',
    expiry: '09/28',
    hardwareToken: 'enc_hsm_gtb_09418240',
    monthlySpendLimit: 250000,
    status: 'active',
  },
  {
    id: 'card_02',
    bankName: 'Kuda MFB',
    cardType: 'Visa',
    last4: '1104',
    expiry: '11/27',
    hardwareToken: 'enc_hsm_kuda_8819024',
    monthlySpendLimit: 120000,
    status: 'active',
  },
  {
    id: 'card_03',
    bankName: 'Access Bank',
    cardType: 'Visa',
    last4: '4242',
    expiry: '04/29',
    hardwareToken: 'enc_hsm_acc_4410298',
    monthlySpendLimit: 300000,
    status: 'active',
  },
];

export const billerCatalog: BillerCatalogItem[] = [
  {
    id: 'cat_netflix',
    name: 'Netflix Subscription',
    category: 'subscriptions',
    categoryLabel: 'Streaming Entertainment',
    icon: 'tv',
    identifierLabel: 'Netflix Account Email',
    identifierPlaceholder: 'user@example.com',
    plans: [
      { id: 'net_mobile', name: 'Mobile Plan', amount: 2200, description: '1 Screen, SD Quality on phone/tablet' },
      { id: 'net_basic', name: 'Basic Plan', amount: 3500, description: '1 Screen, 720p HD on all devices' },
      { id: 'net_standard', name: 'Standard HD', amount: 4500, description: '2 Screens, 1080p Full HD' },
      { id: 'net_premium', name: 'Premium 4K Ultra HD', amount: 5500, description: '4 Screens, 4K HDR + Spatial Audio' },
    ],
  },
  {
    id: 'cat_dstv',
    name: 'DStv / MultiChoice',
    category: 'subscriptions',
    categoryLabel: 'Cable Television',
    icon: 'live_tv',
    identifierLabel: 'SmartCard / IUC Number',
    identifierPlaceholder: 'e.g. 1029482012',
    plans: [
      { id: 'dstv_yanga', name: 'DStv Yanga Bouquet', amount: 5100, description: '85+ Channels including local entertainment' },
      { id: 'dstv_confam', name: 'DStv Confam Bouquet', amount: 9300, description: '105+ Channels with lifestyle and movies' },
      { id: 'dstv_compact', name: 'DStv Compact', amount: 15700, description: '130+ Channels, Premier League and WWE' },
      { id: 'dstv_compact_plus', name: 'DStv Compact Plus', amount: 25000, description: '145+ Channels with Champions League' },
      { id: 'dstv_premium', name: 'DStv Premium Bouquet', amount: 37000, description: '160+ Channels, all live sports and Showmax' },
    ],
  },
  {
    id: 'cat_electric',
    name: 'Electricity / NEPA (Prepaid & Postpaid)',
    category: 'utilities',
    categoryLabel: 'Power Utilities',
    icon: 'bolt',
    identifierLabel: 'Prepaid Meter Number',
    identifierPlaceholder: 'e.g. 04291840192',
    plans: [
      { id: 'elec_20k', name: 'Standard Utility Units', amount: 20000, description: 'Approx 90 - 110 kWh prepaid token' },
      { id: 'elec_35k', name: 'Heavy Domestic Household', amount: 35000, description: 'Approx 170 - 200 kWh with generator backup' },
      { id: 'elec_50k', name: 'High-Consumption Villa', amount: 50000, description: 'Approx 260 - 290 kWh dual-meter reserve' },
    ],
  },
  {
    id: 'cat_internet',
    name: 'Fiber & Broadband Internet',
    category: 'telecom_data',
    categoryLabel: 'Data & Connectivity',
    icon: 'wifi',
    identifierLabel: 'Line / Account Number',
    identifierPlaceholder: 'e.g. 08039912044',
    plans: [
      { id: 'mtn_5g_100gb', name: 'MTN 5G 100GB Monthly', amount: 15000, description: 'Uncapped speeds for remote work' },
      { id: 'mtn_5g_200gb', name: 'MTN 5G 200GB Fiber Plan', amount: 25000, description: 'High-speed household broadband' },
      { id: 'starlink_res', name: 'Starlink Nigeria Residential', amount: 38000, description: 'Unlimited high-speed satellite broadband' },
    ],
  },
  {
    id: 'cat_rent',
    name: 'Annual Rent Sinking Reserve',
    category: 'housing_rent',
    categoryLabel: 'Housing & Rent',
    icon: 'home',
    identifierLabel: 'Rent Sinking Vault Note',
    identifierPlaceholder: 'e.g. Stanbic Rent MMF Vault',
    plans: [
      { id: 'rent_100k', name: 'Monthly ₦100,000 Allocation', amount: 100000, description: 'Targets ₦1.2M annual tenancy budget' },
      { id: 'rent_200k', name: 'Monthly ₦200,000 Allocation', amount: 200000, description: 'Targets ₦2.4M annual tenancy budget (14% yield)' },
      { id: 'rent_350k', name: 'Monthly ₦350,000 Allocation', amount: 350000, description: 'Targets ₦4.2M luxury flat tenancy budget' },
    ],
  },
  {
    id: 'cat_school',
    name: "Children's School Fees Reserve",
    category: 'education',
    categoryLabel: 'Education Reserve',
    icon: 'school',
    identifierLabel: 'Education Vault Tag',
    identifierPlaceholder: 'e.g. GTBank Termly Tuition',
    plans: [
      { id: 'sch_50k', name: '₦50,000 Monthly Sinking', amount: 50000, description: 'Termly budget ₦150k per child' },
      { id: 'sch_100k', name: '₦100,000 Monthly Sinking', amount: 100000, description: 'Termly budget ₦300k per child' },
      { id: 'sch_200k', name: '₦200,000 Monthly Sinking', amount: 200000, description: 'High-grade private school termly tuition' },
    ],
  },
];

export const initialBillRoutes: BillRouteItem[] = [
  {
    id: 'bill_01',
    name: 'Ikeja Electric (IKEDC) Light Bill',
    category: 'utilities',
    categoryLabel: 'Electricity & Utilities',
    icon: 'bolt',
    targetAmount: 35000,
    maxSpendingCap: 40000,
    billerIdentifier: '04291840192',
    assignedPaymentSourceId: 'card_01',
    assignedPaymentSourceName: 'GTBank (•••• 0491)',
    selectedPlanId: 'elec_35k',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 1, 2026',
    description: 'Prepaid meter token auto-generated and texted instantly.',
  },
  {
    id: 'bill_02',
    name: 'MTN 5G Broadband Internet',
    category: 'telecom_data',
    categoryLabel: 'Data & WiFi',
    icon: 'wifi',
    targetAmount: 25000,
    maxSpendingCap: 30000,
    billerIdentifier: '08039912044',
    assignedPaymentSourceId: 'card_02',
    assignedPaymentSourceName: 'Kuda Virtual (•••• 1104)',
    selectedPlanId: 'mtn_5g_200gb',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'Apr 28, 2026',
    description: 'Home 200GB monthly fiber renewal.',
  },
  {
    id: 'bill_03',
    name: 'Netflix Premium 4K Ultra HD',
    category: 'subscriptions',
    categoryLabel: 'Streaming Entertainment',
    icon: 'tv',
    targetAmount: 5500,
    maxSpendingCap: 7000,
    billerIdentifier: 'netflix-bello@mymoney.ng',
    assignedPaymentSourceId: 'card_02',
    assignedPaymentSourceName: 'Kuda Virtual (•••• 1104)',
    selectedPlanId: 'net_premium',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 5, 2026',
    description: '4 Screens, 4K HDR subscription option.',
  },
  {
    id: 'bill_04',
    name: 'DStv Compact Plus',
    category: 'subscriptions',
    categoryLabel: 'Cable Television',
    icon: 'live_tv',
    targetAmount: 25000,
    maxSpendingCap: 30000,
    billerIdentifier: '1029482012',
    assignedPaymentSourceId: 'card_01',
    assignedPaymentSourceName: 'GTBank (•••• 0491)',
    selectedPlanId: 'dstv_compact_plus',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 2, 2026',
    description: 'Premier League + Champions League sports package.',
  },
  {
    id: 'bill_05',
    name: 'Annual Rent Savings Reserve',
    category: 'housing_rent',
    categoryLabel: 'Housing & Rent',
    icon: 'home',
    targetAmount: 200000,
    maxSpendingCap: 200000,
    billerIdentifier: 'Stanbic Rent MMF Vault',
    assignedPaymentSourceId: 'card_03',
    assignedPaymentSourceName: 'Access Bank (•••• 4242)',
    selectedPlanId: 'rent_200k',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 1, 2026',
    description: 'Monthly rent sinking fund earning 14% daily compound interest.',
  },
  {
    id: 'bill_06',
    name: "Children's School Fees Reserve",
    category: 'education',
    categoryLabel: 'Education Reserve',
    icon: 'school',
    targetAmount: 100000,
    maxSpendingCap: 100000,
    billerIdentifier: 'GTBank Education Vault',
    assignedPaymentSourceId: 'card_01',
    assignedPaymentSourceName: 'GTBank (•••• 0491)',
    selectedPlanId: 'sch_100k',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 1, 2026',
    description: 'Termly school fees accumulation fund.',
  },
];
