import { BillRouteItem, PaydayInflowRule } from '@/types/payday';

export const initialPaydayRules: PaydayInflowRule = {
  minInflowThreshold: 500000,
  narrationKeywords: ['SALARY', 'PAYROLL', 'EARNINGS', 'CONTRACT', 'INFLOW', 'SETTLEMENT'],
  executionMode: 'autonomous',
  primaryReceivingNodeId: 'node_gtb_01',
  residualStrategy: 'sweep_to_savings',
  globalFreezeActive: false,
};

export const initialBillRoutes: BillRouteItem[] = [
  {
    id: 'bill_01',
    name: 'Ikeja Electric (IKEDC) Light Bill',
    category: 'utilities',
    categoryLabel: 'Electricity & Utilities',
    icon: 'bolt',
    targetAmount: 35000,
    maxSpendingCap: 40000,
    billerIdentifier: 'Prepaid Meter: 04291840192',
    assignedPaymentSourceId: 'node_gtb_01',
    assignedPaymentSourceName: 'GTBank Checking • 0491',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 1, 2026',
    description: 'Auto-recharge token dispatched to phone instantly.',
  },
  {
    id: 'bill_02',
    name: 'MTN 5G Broadband Internet',
    category: 'telecom_data',
    categoryLabel: 'Data & WiFi',
    icon: 'wifi',
    targetAmount: 25000,
    maxSpendingCap: 30000,
    billerIdentifier: 'Fiber Line: 08039912044',
    assignedPaymentSourceId: 'node_kuda_01',
    assignedPaymentSourceName: 'Kuda Virtual Card • 1104',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'Apr 28, 2026',
    description: 'Home 200GB monthly fiber renewal.',
  },
  {
    id: 'bill_03',
    name: 'Netflix Premium 4K',
    category: 'subscriptions',
    categoryLabel: 'Streaming & Media',
    icon: 'tv',
    targetAmount: 5500,
    maxSpendingCap: 7000,
    billerIdentifier: 'Account: netflix-bello@mymoney.ng',
    assignedPaymentSourceId: 'node_kuda_01',
    assignedPaymentSourceName: 'Kuda Virtual Card • 1104',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 5, 2026',
    description: 'Family 4-screen monthly subscription.',
  },
  {
    id: 'bill_04',
    name: 'DSTV Premium + Showmax',
    category: 'subscriptions',
    categoryLabel: 'Entertainment',
    icon: 'live_tv',
    targetAmount: 29500,
    maxSpendingCap: 35000,
    billerIdentifier: 'Smartcard: 1029482012',
    assignedPaymentSourceId: 'node_gtb_01',
    assignedPaymentSourceName: 'GTBank Checking • 0491',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 2, 2026',
    description: 'Monthly sports & news bouquet.',
  },
  {
    id: 'bill_05',
    name: 'Annual Rent Savings Reserve',
    category: 'housing_rent',
    categoryLabel: 'Rent & Housing',
    icon: 'home',
    targetAmount: 200000,
    maxSpendingCap: 200000,
    billerIdentifier: 'Target: Stanbic High-Yield Vault (14% p.a.)',
    assignedPaymentSourceId: 'node_stanbic_01',
    assignedPaymentSourceName: 'Stanbic IBTC • 8820',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 1, 2026',
    description: 'Monthly rent sinking fund earning 14% daily interest.',
  },
  {
    id: 'bill_06',
    name: 'School Fees Sinking Fund',
    category: 'education',
    categoryLabel: 'Children & Education',
    icon: 'school',
    targetAmount: 100000,
    maxSpendingCap: 100000,
    billerIdentifier: 'Target: GTBank Education Vault',
    assignedPaymentSourceId: 'node_gtb_01',
    assignedPaymentSourceName: 'GTBank Checking • 0491',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 1, 2026',
    description: 'Next term tuition reserve for 2 children.',
  },
  {
    id: 'bill_07',
    name: 'Weekly Groceries & Cooking Gas',
    category: 'living_groceries',
    categoryLabel: 'Living & Food',
    icon: 'shopping_cart',
    targetAmount: 80000,
    maxSpendingCap: 100000,
    billerIdentifier: 'Kuda Pocket #FOOD-SPEND',
    assignedPaymentSourceId: 'node_kuda_01',
    assignedPaymentSourceName: 'Kuda MFB • 1104',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 8, 2026',
    description: 'Dedicated weekly grocery allowance in separate card pocket.',
  },
  {
    id: 'bill_08',
    name: 'Emergency Savings & Wealth Sweeps',
    category: 'wealth_investment',
    categoryLabel: 'Investments & Growth',
    icon: 'trending_up',
    targetAmount: 50000,
    maxSpendingCap: 100000,
    billerIdentifier: 'Sovereign Treasury Vault (14.0% p.a.)',
    assignedPaymentSourceId: 'node_stanbic_01',
    assignedPaymentSourceName: 'Stanbic IBTC • 8820',
    isAutoEnabled: true,
    status: 'active',
    lastSettledDate: 'May 1, 2026',
    description: 'Residual salary auto-swept to compound daily.',
  },
];
